- id: toml-sort
  name: toml-sort
  entry: toml-sort
  args: [--check]
  language: python
  types: [toml]
- id: toml-sort-fix
  name: toml-sort-fix
  entry: toml-sort
  args: [--in-place]
  language: python
  types: [toml]
