name: release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup, Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: x64
      - name: Deploy with Python 3.12
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: |
          python -m pip install -U pip
          python -m pip install wheel
          python -m pip install poetry
          poetry build
          poetry publish
